name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.4
        uses: actions/setup-go@v5
        with:
          go-version: stable
        id: go

      - uses: actions/checkout@v4

      - name: Build
        run: |
          go build -v .

      - name: Test
        run: |
          go test .
