name: Action
on: [push, pull_request]
jobs:
  go-action:
    runs-on: ubuntu-latest
    steps:
      - env:
        OUT_FILE: "test.pdf"
      - uses: actions/checkout@v4
      - name: action
        id: action
        uses: ./
        with:
          in: "test.md"
          out: "$OUT_FILE"
      - name: check result
        run: |
          if test -f "$OUT_FILE"; then
              echo "file exists"
          fi
