name: Action
on: [push, pull_request]
jobs:
  go-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: action
        id: action
        uses: ./
        with:
          in: "test.md"
          out: "test.pdf"
      - name: check result
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: |
          echo "$JOB_CONTEXT\n"
