name: Action
on: [push, pull_request]
env:
  OUT_FILE: test.pdf
jobs:
  go-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: action
        uses: ./
        with:
          in: "test.md"
          out: "$OUT_FILE"
      - name: check result
        run: |
          test -f $OUT_FILE
